name: Post Job to Telegram

on:
  schedule:
    # Runs every 4 hours
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  post-to-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure `requirements.txt` includes all necessary dependencies

      - name: Run Telegram Post Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          SERVER_AUTH_TOKEN: ${{ secrets.SERVER_AUTH_TOKEN }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
        run: |
          python app.py
